version: '3'

networks:
  db:

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pokemon_api
      - POSTGRES_USER=pokemon_api
      - POSTGRES_PASSWORD=pokemon_api
      - MAX_CONNECTIONS=300
    networks:
      - db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
